### ISSUE TITLE
Roadmap for applications

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#34]
Before opening applications (deadline 25.10.19)
- Applications
  - [x] Choose application platform (#33) (Yo to set up)
  - [x] Create application forms (questions, etc) (Yo to set up)
  - [x] Create review criteria (based on application forms) - Bérénice
- Comm
  - [x] Write and publish blog post with Emmy - Malvika will draft, Yo will review with Emmy
  - [x] Prepare email to send to mailing lists (list?), mentioning the pre-application webinar
  - [x] Send emails to mailing lists - 28.10.19
  - [x] Schedule the pre-application webinar
  - [x] Tweet about the program 1 week before the application opens
  - [x] Tweet about the application open
  - [x] Create flyers

When applications are open (25.10.19-end of November)
- Comm
  - [x] Talk at MozFest
  - [x] Distribute flyers at MozFest
  - [x] Tweet about the applications
  - [x] Share on the website and tweet about our stories with MOL
  - [x] Tweet about the pre-application webinar 
  - [x] Send reminder about the pre-application webinar
  - [x] Talk at Biohackathon
  - [x] Distribute flyers at Biohackathon
  - [x] Open table at Biohackathon to discuss about the program and help with applications
- Recruitment
  - [x] Recruit mentors/reviewers
  - [x] Recruit experts

When applications are closed (end of November)
- Reviews
  - [x] Send applications to reviewers
  - [x] Send reminders for reviews a week before deadline
  - [x] Check 
- Comms
  - [x] Send emails to selected candidates
  - [x] Send emails to rejected candidates with invitation to submit next time
  - [x] Add list of mentors on the website
  - [x] Add list of experts on the website
  - [x] Add list of projects on the website

*Feel free to edit this issues with new tasks, add deadlines and assign people to task*
